//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18213
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistoryQIPCollector_TestProject.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HistoryQIPCollector_TestProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --------------------------------------&lt;-
        ///Женя Тарасов (10:23:52 22/04/2010)
        ///госы 27го если ты не сдал
        ///123
        ///456
        ///
        ///
        ///
        ///
        ///--------------------------------------&gt;-
        ///S_H_U_R_I_K (10:28:03 22/04/2010)
        ///ок)спс)Сдал)А кто ещё с тобой сдает?
        ///123
        ///
        ///
        ///
        ///124
        ///14
        ///
        ///--------------------------------------&gt;-
        ///abataloff (12:26:21 19/03/2013)
        ///до скольки тренажерка работает?
        ///
        ///--------------------------------------&lt;-
        ///Женя Тарасов (12:26:26 19/03/2013)
        ///до 9-10
        ///
        ///
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string _12341765 {
            get {
                return ResourceManager.GetString("_12341765", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --------------------------------------&lt;-
        ///Женя Тарасов (10:23:52 22/04/2010)
        ///госы 27го если ты не сдал
        ///123
        ///456
        ///
        ///
        ///
        ///
        ///--------------------------------------&gt;-
        ///S_H_U_R_I_K (10:28:03 22/04/2010)
        ///ок)спс)Сдал)А кто ещё с тобой сдает?
        ///
        ///--------------------------------------&gt;-
        ///abataloff (12:26:21 19/03/2013)
        ///до скольки тренажерка работает?
        ///
        ///--------------------------------------&lt;-
        ///Женя Тарасов (12:26:26 19/03/2013)
        ///до 9-10
        ///
        ///
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string _12348765 {
            get {
                return ResourceManager.GetString("_12348765", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --------------------------------------&lt;-
        ///Женя Тарасов (10:23:52 22/04/2010)
        ///госы 27го если ты не сдал
        ///
        ///--------------------------------------&gt;-
        ///S_H_U_R_I_K (10:28:03 22/04/2010)
        ///ок)спс)Сдал)А кто ещё с тобой сдает?
        ///
        ///--------------------------------------&gt;-
        ///abataloff (12:26:21 19/03/2013)
        ///до скольки тренажерка работает?
        ///
        ///--------------------------------------&lt;-
        ///Женя Тарасов (12:26:26 19/03/2013)
        ///до 9-10
        ///
        ///.
        /// </summary>
        internal static string _2933684 {
            get {
                return ResourceManager.GetString("_2933684", resourceCulture);
            }
        }
    }
}
